SELECT * FROM PRODUTO

INSERT INTO PRODUTO (Descricao) VALUES ('Farinha')
INSERT INTO PRODUTO (Descricao) VALUES ('Açúcar')
INSERT INTO PRODUTO (Descricao) VALUES ('Sal')

SET IDENTITY_INSERT PRODUTO ON

DELETE FROM PRODUTO WHERE ID=3

UPDATE PRODUTO SET Descricao = 'Chocolate' WHERE ID = 1

DROP TABLE PRODUTO

select Id,Descricao from Produto